### ISSUE TITLE
Release Improvements Project

### ISSUE THREAD

**Issue by upodroid** [knative/infra#99]
This is an epic style issue tracking Release Improvements Project:

- Start generating SBOMs:
   -  https://github.com/knative/test-infra/pull/3342 ko 0.11+ generates and attaches SBOMs to docker images.
- Start enabling Workload Identity:
   - knative/test-infra#3448 
   - knative/test-infra#3372
   - https://github.com/istio/test-infra/pull/4180
   - knative/test-infra#3481
   - knative/test-infra#3506
- Delete service account keys
- knative/test-infra#3536   
- Add `cosign` to prow-tests image. 
   - https://github.com/knative/test-infra/pull/3385
- Manage all infra used/touched by the release via Infrastructure as Code
- [SLSA Compliance](https://slsa.dev/spec/v0.1/levels)
   - knative/test-infra#3440 
   - knative/test-infra#3442
   - knative/test-infra#3468
- Start signing nightly builds:
   - https://github.com/knative/hack/pull/198/ 
   - nightly/release docker images
      - [x] knative.dev/serving
      - [x] knative.dev/net-certmanager
      - [x] knative.dev/net-contour
      - [x] knative.dev/net-http01
      - [x] knative.dev/net-istio
      - [x] knative.dev/net-kourier
      - [x] knative.dev/net-gateway-api
      - [x] knative.dev/eventing
      - [x] knative.dev/sample-controller
      - [x] knative.dev/eventing-ceph
      - [x] knative.dev/eventing-kogito
      - [x] knative.dev/eventing-rabbitmq
      - [x] knative.dev/sample-source
      - [x] knative.dev/eventing-kafka
      - [x] knative.dev/eventing-redis
      - [x] knative.dev/eventing-github
      - [X] knative.dev/eventing-gitlab
      - [x] knative.dev/eventing-kafka-broker
      - [x] knative.dev/eventing-autoscaler-keda
   - nightly/release kn binary builds
      - [X] knative.dev/client
      - [x] knative.dev/kn-plugin-admin
      - [x] knative.dev/kn-plugin-event
      - [ ] knative.dev/kn-plugin-source-kafka
      - [ ] knative.dev/kn-plugin-source-kamelet
      - [x] knative.dev/kn-plugin-quickstart
      - [x] knative.dev/kn-plugin-func  
- Create signing infrastructure:
   - ~Generate tests/dev keys~
      - ~https://github.com/knative/test-infra/pull/3385~
   - ~Generate nightly keys~
      - ~https://github.com/knative/test-infra/pull/3385~
   - Generate Keyless Signing service accounts
      - https://github.com/knative/test-infra/pull/3516
- Tighten IAM permissions for release/nightly project 
- https://github.com/knative/test-infra/issues/3135
- Docs:
  - https://github.com/knative/docs/pull/5272
